name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [sphinx-docs] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        source: docs/source  # Specify the directory containing conf.py
      env:
        SPHINXOPTS: "-c docs/source"  # Set the Sphinx options to use the correct path
